name: Expo Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    env:
      EXPO_OWNER: ${{ secrets.EXPO_OWNER }}
      EXPO_SLUG: ${{ secrets.EXPO_SLUG }}
      BUNDLE_IDENTIFIER: ${{ secrets.BUNDLE_IDENTIFIER }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'yarn.lock') }}
      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile
      - uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Publish
        run: expo publish
